//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome_Control.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dome_Control.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Difference.
        /// </summary>
        public static string AngleDiffLabel {
            get {
                return ResourceManager.GetString("AngleDiffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino Debug Mode.
        /// </summary>
        public static string ArduinoDebugMode {
            get {
                return ResourceManager.GetString("ArduinoDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootloader COM.
        /// </summary>
        public static string BootloaderCOMLabel {
            get {
                return ResourceManager.GetString("BootloaderCOMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelDownloadButton {
            get {
                return ResourceManager.GetString("CancelDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml File (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        public static string ConfigLabel {
            get {
                return ResourceManager.GetString("ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ConnectionGroup_Label {
            get {
                return ResourceManager.GetString("ConnectionGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continous Slewing.
        /// </summary>
        public static string ContinuousSlewingLabel {
            get {
                return ResourceManager.GetString("ContinuousSlewingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ControlTabDef {
            get {
                return ResourceManager.GetString("ControlTabDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugLabel {
            get {
                return ResourceManager.GetString("DebugLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugTabDef {
            get {
                return ResourceManager.GetString("DebugTabDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dome connected to telescope:.
        /// </summary>
        public static string DomeConnectionLabel {
            get {
                return ResourceManager.GetString("DomeConnectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dome Position.
        /// </summary>
        public static string DomePositionLabel {
            get {
                return ResourceManager.GetString("DomePositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Position with Telescope.
        /// </summary>
        public static string DomeSyncLabel {
            get {
                return ResourceManager.GetString("DomeSyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Clearing Arduino Debug Mode.
        /// </summary>
        public static string ErrClearingDebugMode {
            get {
                return ResourceManager.GetString("ErrClearingDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get Dome Azimuth position.
        /// </summary>
        public static string ErrGettingAzimuth {
            get {
                return ResourceManager.GetString("ErrGettingAzimuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVRDUDE fails, impossible to connect to avrdude.
        /// </summary>
        public static string Error_AVRDUDE {
            get {
                return ResourceManager.GetString("Error_AVRDUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help File not Found.
        /// </summary>
        public static string Error_HelpFileNotFound {
            get {
                return ResourceManager.GetString("Error_HelpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorReading Configuration File.
        /// </summary>
        public static string Error_ReadConfFile {
            get {
                return ResourceManager.GetString("Error_ReadConfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating GUI Language.
        /// </summary>
        public static string Error_UpdateGUI {
            get {
                return ResourceManager.GetString("Error_UpdateGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Setting Arduino Debug Mode.
        /// </summary>
        public static string ErrSetDebugMode {
            get {
                return ResourceManager.GetString("ErrSetDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language.
        /// </summary>
        public static string LanguageUILabel {
            get {
                return ResourceManager.GetString("LanguageUILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Configuration.
        /// </summary>
        public static string LoadConfigButtonLabel {
            get {
                return ResourceManager.GetString("LoadConfigButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LoadNewFWButton {
            get {
                return ResourceManager.GetString("LoadNewFWButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load New Firmware in Arduino.
        /// </summary>
        public static string LoadNewFWLabel {
            get {
                return ResourceManager.GetString("LoadNewFWLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Console.
        /// </summary>
        public static string MenuItemDebugConsole {
            get {
                return ResourceManager.GetString("MenuItemDebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExitName {
            get {
                return ResourceManager.GetString("MenuItemExitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItemFileName {
            get {
                return ResourceManager.GetString("MenuItemFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemHelpAbout {
            get {
                return ResourceManager.GetString("MenuItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelpName {
            get {
                return ResourceManager.GetString("MenuItemHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuItemOptions {
            get {
                return ResourceManager.GetString("MenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuItemOptionsName {
            get {
                return ResourceManager.GetString("MenuItemOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to PARK the dome, are you sure you want to proceed?.
        /// </summary>
        public static string MsgParkWarning {
            get {
                return ResourceManager.GetString("MsgParkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to STOP the dome slewing, are you sure you want to proceed?.
        /// </summary>
        public static string MsgStopWarning {
            get {
                return ResourceManager.GetString("MsgStopWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arduino Firmware.
        /// </summary>
        public static string NewFWLabel {
            get {
                return ResourceManager.GetString("NewFWLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Mode.
        /// </summary>
        public static string RunTabDef {
            get {
                return ResourceManager.GetString("RunTabDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration.
        /// </summary>
        public static string SaveConfigButtonLabel {
            get {
                return ResourceManager.GetString("SaveConfigButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slewing.
        /// </summary>
        public static string SlewingIndicatorLabel {
            get {
                return ResourceManager.GetString("SlewingIndicatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slewing.
        /// </summary>
        public static string SlewingLabel {
            get {
                return ResourceManager.GetString("SlewingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string StatusBar_Connected {
            get {
                return ResourceManager.GetString("StatusBar_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string StatusBar_Disconnected {
            get {
                return ResourceManager.GetString("StatusBar_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Slewing.
        /// </summary>
        public static string StepSlewingLabel {
            get {
                return ResourceManager.GetString("StepSlewingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telescope Position.
        /// </summary>
        public static string TelescopeLabel {
            get {
                return ResourceManager.GetString("TelescopeLabel", resourceCulture);
            }
        }
    }
}
