//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome_Control.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dome_Control.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Difference.
        /// </summary>
        internal static string AngleDiffLabel {
            get {
                return ResourceManager.GetString("AngleDiffLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ARA {
            get {
                object obj = ResourceManager.GetObject("ARA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ARA2 {
            get {
                object obj = ResourceManager.GetObject("ARA2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstroIcon1 {
            get {
                object obj = ResourceManager.GetObject("AstroIcon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstroIcon2 {
            get {
                object obj = ResourceManager.GetObject("AstroIcon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstroIcon3 {
            get {
                object obj = ResourceManager.GetObject("AstroIcon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootloader COM.
        /// </summary>
        internal static string BootloaderCOMLabel {
            get {
                return ResourceManager.GetString("BootloaderCOMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelDownloadButton {
            get {
                return ResourceManager.GetString("CancelDownloadButton", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ConnectedImg {
            get {
                object obj = ResourceManager.GetObject("ConnectedImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string ConnectionGroup_Label {
            get {
                return ResourceManager.GetString("ConnectionGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string ControlTabDef {
            get {
                return ResourceManager.GetString("ControlTabDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugLabel {
            get {
                return ResourceManager.GetString("DebugLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugTabDef {
            get {
                return ResourceManager.GetString("DebugTabDef", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DisconnectedImg {
            get {
                object obj = ResourceManager.GetObject("DisconnectedImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dome Position.
        /// </summary>
        internal static string DomePositionLabel {
            get {
                return ResourceManager.GetString("DomePositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVRDUDE fails, impossible to connect to avrdude.
        /// </summary>
        internal static string Error_AVRDUDE {
            get {
                return ResourceManager.GetString("Error_AVRDUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help File not Found.
        /// </summary>
        internal static string Error_HelpFileNotFound {
            get {
                return ResourceManager.GetString("Error_HelpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorReading Configuration File.
        /// </summary>
        internal static string Error_ReadConfFile {
            get {
                return ResourceManager.GetString("Error_ReadConfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating GUI Language.
        /// </summary>
        internal static string Error_UpdateGUI {
            get {
                return ResourceManager.GetString("Error_UpdateGUI", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string LoadNewFWButton {
            get {
                return ResourceManager.GetString("LoadNewFWButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load New Firmware in Arduino.
        /// </summary>
        internal static string LoadNewFWLabel {
            get {
                return ResourceManager.GetString("LoadNewFWLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuItemExitName {
            get {
                return ResourceManager.GetString("MenuItemExitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuItemFileName {
            get {
                return ResourceManager.GetString("MenuItemFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuItemHelpAbout {
            get {
                return ResourceManager.GetString("MenuItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuItemHelpName {
            get {
                return ResourceManager.GetString("MenuItemHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MenuItemOptionsName {
            get {
                return ResourceManager.GetString("MenuItemOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arduino Firmware.
        /// </summary>
        internal static string NewFWLabel {
            get {
                return ResourceManager.GetString("NewFWLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Mode.
        /// </summary>
        internal static string RunTabDef {
            get {
                return ResourceManager.GetString("RunTabDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string StatusBar_Connected {
            get {
                return ResourceManager.GetString("StatusBar_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string StatusBar_Disconnected {
            get {
                return ResourceManager.GetString("StatusBar_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telescope Position.
        /// </summary>
        internal static string TelescopeLabel {
            get {
                return ResourceManager.GetString("TelescopeLabel", resourceCulture);
            }
        }
    }
}
